// Generated from DND 5E Data/5e-SRD-Magic-Items.json (2014 SRD).
// The NON BATTLE magic items only (see DND 5E Data/NON BATTLE/).
// Inert catalog entries: they do nothing in battle, they just sit in inventory.
// Regenerate from the NON BATTLE folder, do not hand-edit.
export const MAGIC_ITEMS = [
  {"id": "amulet-of-proof-against-detection-and-location", "name": "Amulet of Proof against Detection and Location", "rarity": "Uncommon", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "amulet-of-the-planes", "name": "Amulet of the Planes", "rarity": "Very Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "apparatus-of-the-crab", "name": "Apparatus of the Crab", "rarity": "Legendary", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "bag-of-beans", "name": "Bag of Beans", "rarity": "Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "bag-of-devouring", "name": "Bag of Devouring", "rarity": "Very Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "bag-of-holding", "name": "Bag of Holding", "rarity": "Uncommon", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "boots-of-elvenkind", "name": "Boots of Elvenkind", "rarity": "Uncommon", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "boots-of-levitation", "name": "Boots of Levitation", "rarity": "Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "boots-of-striding-and-springing", "name": "Boots of Striding and Springing", "rarity": "Uncommon", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "boots-of-the-winterlands", "name": "Boots of the Winterlands", "rarity": "Uncommon", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "broom-of-flying", "name": "Broom of Flying", "rarity": "Uncommon", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "candle-of-invocation", "name": "Candle of Invocation", "rarity": "Very Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "cape-of-the-mountebank", "name": "Cape of the Mountebank", "rarity": "Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "carpet-of-flying", "name": "Carpet of Flying", "rarity": "Very Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "carpet-of-flying-3x5", "name": "Carpet of Flying (3 ft. \u00d7 5 ft.)", "rarity": "Very Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "carpet-of-flying-4x6", "name": "Carpet of Flying (4 ft. \u00d7 6 ft.)", "rarity": "Very Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "carpet-of-flying-5x7", "name": "Carpet of Flying (5 ft. \u00d7 7 ft.)", "rarity": "Very Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "carpet-of-flying-6x9", "name": "Carpet of Flying (6 ft. \u00d7 9 ft.)", "rarity": "Very Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "chime-of-opening", "name": "Chime of Opening", "rarity": "Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "cloak-of-elvenkind", "name": "Cloak of Elvenkind", "rarity": "Uncommon", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "cloak-of-the-bat", "name": "Cloak of the Bat", "rarity": "Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "cloak-of-the-manta-ray", "name": "Cloak of the Manta Ray", "rarity": "Uncommon", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "crystal-ball", "name": "Crystal Ball", "rarity": "Very Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "crystal-ball-of-mind-reading", "name": "Crystal Ball of Mind Reading", "rarity": "Legendary", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "crystal-ball-of-telepathy", "name": "Crystal Ball of Telepathy", "rarity": "Legendary", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "crystal-ball-of-true-seeing", "name": "Crystal Ball of True Seeing", "rarity": "Legendary", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "cubic-gate", "name": "Cubic Gate", "rarity": "Legendary", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "decanter-of-endless-water", "name": "Decanter of Endless Water", "rarity": "Uncommon", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "deck-of-illusions", "name": "Deck of Illusions", "rarity": "Uncommon", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "deck-of-many-things", "name": "Deck of Many Things", "rarity": "Legendary", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "dimensional-shackles", "name": "Dimensional Shackles", "rarity": "Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "dust-of-disappearance", "name": "Dust of Disappearance", "rarity": "Uncommon", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "dust-of-dryness", "name": "Dust of Dryness", "rarity": "Uncommon", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "efficient-quiver", "name": "Efficient Quiver", "rarity": "Uncommon", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "eyes-of-charming", "name": "Eyes of Charming", "rarity": "Uncommon", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "eyes-of-minute-seeing", "name": "Eyes of Minute Seeing", "rarity": "Uncommon", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "eyes-of-the-eagle", "name": "Eyes of the Eagle", "rarity": "Uncommon", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "feather-token", "name": "Feather Token", "rarity": "Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "feather-token-anchor", "name": "Anchor Feather Token", "rarity": "Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "feather-token-bird", "name": "Bird Feather Token", "rarity": "Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "feather-token-fan", "name": "Fan Feather Token", "rarity": "Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "feather-token-swan-boat", "name": "Swan Boat Feather Token", "rarity": "Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "feather-token-tree", "name": "Tree Feather Token", "rarity": "Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "figurine-of-wondrous-power", "name": "Figurine of Wondrous Power", "rarity": "Varies", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "figurine-of-wondrous-power-ebony-fly", "name": "Ebony Fly Figurine of Wondrous Power", "rarity": "Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "figurine-of-wondrous-power-serpentine-owl", "name": "Serpentine Owl Figurine of Wondrous Power", "rarity": "Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "figurine-of-wondrous-power-silver-raven", "name": "Silver Raven Figurine of Wondrous Power", "rarity": "Uncommon", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "folding-boat", "name": "Folding Boat", "rarity": "Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "gem-of-seeing", "name": "Gem of Seeing", "rarity": "Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "gloves-of-swimming-and-climbing", "name": "Gloves of Swimming and Climbing", "rarity": "Uncommon", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "goggles-of-night", "name": "Goggles of Night", "rarity": "Uncommon", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "handy-haversack", "name": "Handy Haversack", "rarity": "Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "hat-of-disguise", "name": "Hat of Disguise", "rarity": "Uncommon", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "headband-of-intellect", "name": "Headband of Intellect", "rarity": "Uncommon", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "helm-of-comprehending-languages", "name": "Helm of Comprehending Languages", "rarity": "Uncommon", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "helm-of-telepathy", "name": "Helm of Telepathy", "rarity": "Uncommon", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "helm-of-teleportation", "name": "Helm of Teleportation", "rarity": "Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "horseshoes-of-a-zephyr", "name": "Horseshoes of a Zephyr", "rarity": "Very Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "horseshoes-of-speed", "name": "Horseshoes of Speed", "rarity": "Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "immovable-rod", "name": "Immovable Rod", "rarity": "Uncommon", "itemCategory": "Rod", "source": "5e-srd-2014"},
  {"id": "ioun-stone-of-sustenance", "name": "Ioun Stone of Sustenance", "rarity": "Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "lantern-of-revealing", "name": "Lantern of Revealing", "rarity": "Uncommon", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "manual-of-bodily-health", "name": "Manual of Bodily Health", "rarity": "Very Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "manual-of-gainful-exercise", "name": "Manual of Gainful Exercise", "rarity": "Very Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "manual-of-golems", "name": "Manual of Golems", "rarity": "Very Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "manual-of-golems-clay", "name": "Manual of Clay Golems", "rarity": "Very Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "manual-of-golems-flesh", "name": "Manual of Flesh Golems", "rarity": "Very Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "manual-of-golems-iron", "name": "Manual of Iron Golems", "rarity": "Very Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "manual-of-golems-stone", "name": "Manual of Stone Golems", "rarity": "Very Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "manual-of-quickness-of-action", "name": "Manual of Quickness of Action", "rarity": "Very Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "marvelous-pigments", "name": "Marvelous Pigments", "rarity": "Very Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "medallion-of-thoughts", "name": "Medallion of Thoughts", "rarity": "Uncommon", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "necklace-of-adaptation", "name": "Necklace of Adaptation", "rarity": "Uncommon", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "oil-of-etherealness", "name": "Oil of Etherealness", "rarity": "Rare", "itemCategory": "Potion", "source": "5e-srd-2014"},
  {"id": "periapt-of-health", "name": "Periapt of Health", "rarity": "Uncommon", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "periapt-of-proof-against-poison", "name": "Periapt of Proof against Poison", "rarity": "Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "philter-of-love", "name": "Philter of Love", "rarity": "Uncommon", "itemCategory": "Potion", "source": "5e-srd-2014"},
  {"id": "portable-hole", "name": "Portable Hole", "rarity": "Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "potion-of-animal-friendship", "name": "Potion of Animal Friendship", "rarity": "Uncommon", "itemCategory": "Potion", "source": "5e-srd-2014"},
  {"id": "potion-of-clairvoyance", "name": "Potion of Clairvoyance", "rarity": "Rare", "itemCategory": "Potion", "source": "5e-srd-2014"},
  {"id": "potion-of-climbing", "name": "Potion of Climbing", "rarity": "Common", "itemCategory": "Potion", "source": "5e-srd-2014"},
  {"id": "potion-of-flying", "name": "Potion of Flying", "rarity": "Very Rare", "itemCategory": "Potion", "source": "5e-srd-2014"},
  {"id": "potion-of-gaseous-form", "name": "Potion of Gaseous Form", "rarity": "Rare", "itemCategory": "Potion", "source": "5e-srd-2014"},
  {"id": "potion-of-mind-reading", "name": "Potion of Mind Reading", "rarity": "Rare", "itemCategory": "Potion", "source": "5e-srd-2014"},
  {"id": "potion-of-poison", "name": "Potion of Poison", "rarity": "Uncommon", "itemCategory": "Potion", "source": "5e-srd-2014"},
  {"id": "potion-of-water-breathing", "name": "Potion of Water Breathing", "rarity": "Uncommon", "itemCategory": "Potion", "source": "5e-srd-2014"},
  {"id": "restorative-ointment", "name": "Restorative Ointment", "rarity": "Uncommon", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "ring-of-animal-influence", "name": "Ring of Animal Influence", "rarity": "Rare", "itemCategory": "Ring", "source": "5e-srd-2014"},
  {"id": "ring-of-feather-falling", "name": "Ring of Feather Falling", "rarity": "Rare", "itemCategory": "Ring", "source": "5e-srd-2014"},
  {"id": "ring-of-jumping", "name": "Ring of Jumping", "rarity": "Uncommon", "itemCategory": "Ring", "source": "5e-srd-2014"},
  {"id": "ring-of-mind-shielding", "name": "Ring of Mind Shielding", "rarity": "Uncommon", "itemCategory": "Ring", "source": "5e-srd-2014"},
  {"id": "ring-of-swimming", "name": "Ring of Swimming", "rarity": "Uncommon", "itemCategory": "Ring", "source": "5e-srd-2014"},
  {"id": "ring-of-three-wishes", "name": "Ring of Three Wishes", "rarity": "Legendary", "itemCategory": "Ring", "source": "5e-srd-2014"},
  {"id": "ring-of-warmth", "name": "Ring of Warmth", "rarity": "Uncommon", "itemCategory": "Ring", "source": "5e-srd-2014"},
  {"id": "ring-of-water-walking", "name": "Ring of Water Walking", "rarity": "Uncommon", "itemCategory": "Ring", "source": "5e-srd-2014"},
  {"id": "ring-of-x-ray-vision", "name": "Ring of X-ray Vision", "rarity": "Rare", "itemCategory": "Ring", "source": "5e-srd-2014"},
  {"id": "robe-of-eyes", "name": "Robe of Eyes", "rarity": "Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "robe-of-useful-items", "name": "Robe of Useful Items", "rarity": "Uncommon", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "rod-of-rulership", "name": "Rod of Rulership", "rarity": "Rare", "itemCategory": "Rod", "source": "5e-srd-2014"},
  {"id": "rod-of-security", "name": "Rod of Security", "rarity": "Very Rare", "itemCategory": "Rod", "source": "5e-srd-2014"},
  {"id": "rope-of-climbing", "name": "Rope of Climbing", "rarity": "Uncommon", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "slippers-of-spider-climbing", "name": "Slippers of Spider Climbing", "rarity": "Uncommon", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "sovereign-glue", "name": "Sovereign Glue", "rarity": "Legendary", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "stone-of-good-luck-luckstone", "name": "Stone of Good Luck (Luckstone)", "rarity": "Uncommon", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "tome-of-clear-thought", "name": "Tome of Clear Thought", "rarity": "Very Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "tome-of-leadership-and-influence", "name": "Tome of Leadership and Influence", "rarity": "Very Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "tome-of-understanding", "name": "Tome of Understanding", "rarity": "Very Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "universal-solvent", "name": "Universal Solvent", "rarity": "Legendary", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "wand-of-magic-detection", "name": "Wand of Magic Detection", "rarity": "Uncommon", "itemCategory": "Wand", "source": "5e-srd-2014"},
  {"id": "wand-of-secrets", "name": "Wand of Secrets", "rarity": "Uncommon", "itemCategory": "Wand", "source": "5e-srd-2014"},
  {"id": "well-of-many-worlds", "name": "Well of Many Worlds", "rarity": "Legendary", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "winged-boots", "name": "Winged Boots", "rarity": "Uncommon", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
  {"id": "wings-of-flying", "name": "Wings of Flying", "rarity": "Rare", "itemCategory": "Wondrous Items", "source": "5e-srd-2014"},
];

export const magicItemById = (id) =>
  MAGIC_ITEMS.find((item) => item.id === id) || null;
