-- Reconstruct the Roll30 schema that predates the migrations originally kept
-- in this repository. This file deliberately creates only the foundation;
-- later dated migrations add notes, scene objects, templates, and normalized
-- session tokens.

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'Adventurer',
  avatar_url text,
  created_at timestamptz not null default now()
);

create table public.campaigns (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete restrict,
  name text not null check (char_length(name) between 1 and 120),
  system text not null default 'D&D 5e',
  join_code text not null unique default upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8)),
  settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.characters (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  owner_id uuid references public.profiles(id) on delete set null,
  kind text not null default 'pc' check (kind in ('pc', 'npc', 'monster')),
  name text not null,
  sheet jsonb not null default '{}'::jsonb,
  hp_current integer,
  hp_max integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.campaign_assets (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  uploaded_by uuid references public.profiles(id) on delete set null,
  kind text not null check (kind in ('image', 'audio', 'portrait', 'handout')),
  storage_path text not null unique,
  label text not null,
  created_at timestamptz not null default now()
);

create table public.scenes (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  name text not null,
  scene_type text not null default 'playing' check (scene_type in ('playing', 'battle')),
  folder text,
  background_asset_id uuid references public.campaign_assets(id) on delete set null,
  config jsonb not null default '{}'::jsonb,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.campaign_members (
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'player' check (role in ('gm', 'player')),
  character_id uuid references public.characters(id) on delete set null,
  joined_at timestamptz not null default now(),
  primary key (campaign_id, user_id)
);

create table public.sessions (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  scene_id uuid references public.scenes(id) on delete set null,
  status text not null default 'active' check (status in ('active', 'ended')),
  round integer not null default 1 check (round >= 1),
  active_turn integer not null default 0 check (active_turn >= 0),
  state jsonb not null default '{"fog": {}, "walls": [], "lights": [], "tokens": [], "reveals": {}, "initiative": []}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.session_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.sessions(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.items (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  name text not null,
  item_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.character_inventory (
  character_id uuid not null references public.characters(id) on delete cascade,
  item_id uuid not null references public.items(id) on delete cascade,
  quantity integer not null default 1 check (quantity >= 0),
  metadata jsonb not null default '{}'::jsonb,
  primary key (character_id, item_id)
);

create table public.shops (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  npc_id uuid references public.characters(id) on delete set null,
  name text not null,
  settings jsonb not null default '{"mode": "approval", "discount": 0}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.shop_stock (
  shop_id uuid not null references public.shops(id) on delete cascade,
  item_id uuid not null references public.items(id) on delete cascade,
  price integer not null default 0 check (price >= 0),
  quantity integer check (quantity is null or quantity >= 0),
  hidden boolean not null default false,
  primary key (shop_id, item_id)
);

create table public.purchase_requests (
  id uuid primary key default gen_random_uuid(),
  shop_id uuid not null references public.shops(id) on delete cascade,
  character_id uuid not null references public.characters(id) on delete cascade,
  item_id uuid not null references public.items(id) on delete restrict,
  quantity integer not null default 1 check (quantity > 0),
  status text not null default 'pending' check (status in ('pending', 'approved', 'declined', 'completed')),
  requested_by uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table public.messages (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  recipient_id uuid references public.profiles(id) on delete cascade,
  kind text not null default 'message' check (kind in ('message', 'whisper', 'action', 'roll', 'check_request', 'attack')),
  body jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.prompts (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.campaigns(id) on delete cascade,
  created_by uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  body text not null default '',
  options jsonb not null default '[]'::jsonb,
  audience uuid[] not null default '{}'::uuid[],
  status text not null default 'open' check (status in ('open', 'closed')),
  created_at timestamptz not null default now()
);

create table public.prompt_responses (
  prompt_id uuid not null references public.prompts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  response jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  primary key (prompt_id, user_id)
);

create table public.scene_triggers (
  id uuid primary key default gen_random_uuid(),
  scene_id uuid not null references public.scenes(id) on delete cascade,
  name text not null,
  trigger jsonb not null default '{}'::jsonb,
  effects jsonb not null default '[]'::jsonb,
  enabled boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.session_snapshots (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.sessions(id) on delete cascade,
  created_by uuid references public.profiles(id) on delete set null,
  label text not null,
  state jsonb not null,
  created_at timestamptz not null default now()
);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger touch_campaigns_updated_at before update on public.campaigns
for each row execute function public.touch_updated_at();
create trigger touch_characters_updated_at before update on public.characters
for each row execute function public.touch_updated_at();
create trigger touch_scenes_updated_at before update on public.scenes
for each row execute function public.touch_updated_at();

create schema if not exists app_private;
revoke all on schema app_private from public, anon, authenticated;

create or replace function app_private.create_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(
      nullif(new.raw_user_meta_data ->> 'display_name', ''),
      split_part(coalesce(new.email, 'Adventurer'), '@', 1)
    )
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

revoke all on function app_private.create_profile() from public, anon, authenticated;
create trigger on_auth_user_created_profile
after insert on auth.users
for each row execute function app_private.create_profile();

create or replace function public.is_campaign_member(target_campaign uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.campaign_members
    where campaign_id = target_campaign and user_id = (select auth.uid())
  );
$$;

create or replace function public.is_campaign_gm(target_campaign uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.campaign_members
    where campaign_id = target_campaign
      and user_id = (select auth.uid())
      and role = 'gm'
  );
$$;

revoke all on function public.is_campaign_member(uuid) from public, anon;
revoke all on function public.is_campaign_gm(uuid) from public, anon;
grant execute on function public.is_campaign_member(uuid) to authenticated;
grant execute on function public.is_campaign_gm(uuid) to authenticated;

create or replace function public.create_roll30_campaign(campaign_name text)
returns public.campaigns
language plpgsql
security definer
set search_path = public
as $$
declare
  actor uuid := auth.uid();
  result public.campaigns;
begin
  if actor is null then raise exception 'Authentication required'; end if;
  if nullif(btrim(campaign_name), '') is null then raise exception 'Campaign name is required'; end if;
  insert into public.profiles (id, display_name)
  values (
    actor,
    coalesce(
      nullif(auth.jwt() -> 'user_metadata' ->> 'display_name', ''),
      split_part(coalesce(auth.jwt() ->> 'email', 'Adventurer'), '@', 1)
    )
  ) on conflict (id) do nothing;
  insert into public.campaigns (owner_id, name)
  values (actor, btrim(campaign_name)) returning * into result;
  insert into public.campaign_members (campaign_id, user_id, role)
  values (result.id, actor, 'gm');
  return result;
end;
$$;

create or replace function public.join_roll30_campaign(campaign_code text)
returns public.campaigns
language plpgsql
security definer
set search_path = public
as $$
declare
  actor uuid := auth.uid();
  result public.campaigns;
begin
  if actor is null then raise exception 'Authentication required'; end if;
  select * into result from public.campaigns where join_code = upper(btrim(campaign_code));
  if result.id is null then raise exception 'Campaign not found'; end if;
  insert into public.profiles (id, display_name)
  values (
    actor,
    coalesce(
      nullif(auth.jwt() -> 'user_metadata' ->> 'display_name', ''),
      split_part(coalesce(auth.jwt() ->> 'email', 'Adventurer'), '@', 1)
    )
  ) on conflict (id) do nothing;
  insert into public.campaign_members (campaign_id, user_id, role)
  values (result.id, actor, 'player') on conflict (campaign_id, user_id) do nothing;
  return result;
end;
$$;

create or replace function public.change_roll30_hp(target_character uuid, delta integer)
returns public.characters
language plpgsql
security definer
set search_path = public
as $$
declare
  result public.characters;
begin
  select * into result from public.characters where id = target_character for update;
  if result.id is null then raise exception 'Character not found'; end if;
  if not (public.is_campaign_gm(result.campaign_id) or result.owner_id is not distinct from auth.uid()) then
    raise exception 'Not permitted';
  end if;
  update public.characters
  set hp_current = greatest(0, least(coalesce(result.hp_max, 999999), coalesce(result.hp_current, 0) + delta)),
      updated_at = now()
  where id = target_character returning * into result;
  return result;
end;
$$;

create or replace function public.resolve_roll30_purchase(request_id uuid, approve boolean)
returns public.purchase_requests
language plpgsql
security definer
set search_path = public
as $$
declare
  request_row public.purchase_requests;
  shop_row public.shops;
  stock_row public.shop_stock;
  character_row public.characters;
  gp integer;
  total integer;
begin
  select * into request_row from public.purchase_requests where id = request_id for update;
  if request_row.id is null then raise exception 'Purchase request not found'; end if;
  select * into shop_row from public.shops where id = request_row.shop_id;
  if not public.is_campaign_gm(shop_row.campaign_id) then raise exception 'Only the GM can resolve purchases'; end if;
  if request_row.status <> 'pending' then raise exception 'Purchase request is already resolved'; end if;
  if not approve then
    update public.purchase_requests set status = 'declined', resolved_at = now()
    where id = request_id returning * into request_row;
    return request_row;
  end if;
  select * into stock_row from public.shop_stock
  where shop_id = request_row.shop_id and item_id = request_row.item_id for update;
  if stock_row.item_id is null then raise exception 'Item is no longer stocked'; end if;
  if stock_row.quantity is not null and stock_row.quantity < request_row.quantity then raise exception 'Not enough stock'; end if;
  select * into character_row from public.characters where id = request_row.character_id for update;
  gp := coalesce((character_row.sheet -> 'currency' ->> 'gp')::integer, 0);
  total := stock_row.price * request_row.quantity;
  if gp < total then raise exception 'Character cannot afford this purchase'; end if;
  update public.characters
  set sheet = jsonb_set(character_row.sheet, '{currency,gp}', to_jsonb(gp - total), true), updated_at = now()
  where id = character_row.id;
  insert into public.character_inventory (character_id, item_id, quantity)
  values (character_row.id, request_row.item_id, request_row.quantity)
  on conflict (character_id, item_id) do update
  set quantity = public.character_inventory.quantity + excluded.quantity;
  if stock_row.quantity is not null then
    update public.shop_stock set quantity = quantity - request_row.quantity
    where shop_id = stock_row.shop_id and item_id = stock_row.item_id;
  end if;
  update public.purchase_requests set status = 'completed', resolved_at = now()
  where id = request_id returning * into request_row;
  return request_row;
end;
$$;

revoke all on function public.create_roll30_campaign(text) from public, anon;
revoke all on function public.join_roll30_campaign(text) from public, anon;
revoke all on function public.change_roll30_hp(uuid, integer) from public, anon;
revoke all on function public.resolve_roll30_purchase(uuid, boolean) from public, anon;
grant execute on function public.create_roll30_campaign(text) to authenticated;
grant execute on function public.join_roll30_campaign(text) to authenticated;
grant execute on function public.change_roll30_hp(uuid, integer) to authenticated;
grant execute on function public.resolve_roll30_purchase(uuid, boolean) to authenticated;

alter table public.profiles enable row level security;
alter table public.campaigns enable row level security;
alter table public.campaign_members enable row level security;
alter table public.characters enable row level security;
alter table public.campaign_assets enable row level security;
alter table public.scenes enable row level security;
alter table public.sessions enable row level security;
alter table public.session_events enable row level security;
alter table public.items enable row level security;
alter table public.character_inventory enable row level security;
alter table public.shops enable row level security;
alter table public.shop_stock enable row level security;
alter table public.purchase_requests enable row level security;
alter table public.messages enable row level security;
alter table public.prompts enable row level security;
alter table public.prompt_responses enable row level security;
alter table public.scene_triggers enable row level security;
alter table public.session_snapshots enable row level security;
alter table public.authorized_ips enable row level security;

grant select, update on public.profiles to authenticated;
grant select, insert, update, delete on public.campaigns to authenticated;
grant select, insert, update, delete on public.campaign_members to authenticated;
grant select, insert, update, delete on public.characters to authenticated;
grant select, insert, update, delete on public.campaign_assets to authenticated;
grant select, insert, update, delete on public.scenes to authenticated;
grant select, insert, update, delete on public.sessions to authenticated;
grant select, insert on public.session_events to authenticated;
grant select, insert, update, delete on public.items to authenticated;
grant select, insert, update, delete on public.character_inventory to authenticated;
grant select, insert, update, delete on public.shops to authenticated;
grant select, insert, update, delete on public.shop_stock to authenticated;
grant select, insert, update on public.purchase_requests to authenticated;
grant select, insert on public.messages to authenticated;
grant select, insert, update, delete on public.prompts to authenticated;
grant select, insert, update, delete on public.prompt_responses to authenticated;
grant select, insert, update, delete on public.scene_triggers to authenticated;
grant select, insert, update, delete on public.session_snapshots to authenticated;
revoke all on public.authorized_ips from anon, authenticated;

create policy "read own profile" on public.profiles for select to authenticated
using (id = (select auth.uid()));
create policy "update own profile" on public.profiles for update to authenticated
using (id = (select auth.uid())) with check (id = (select auth.uid()));

create policy "users create owned campaigns" on public.campaigns for insert to authenticated
with check (owner_id = (select auth.uid()));
create policy "members read campaigns" on public.campaigns for select to authenticated
using (public.is_campaign_member(id));
create policy "owners update campaigns" on public.campaigns for update to authenticated
using (owner_id = (select auth.uid())) with check (owner_id = (select auth.uid()));
create policy "owners delete campaigns" on public.campaigns for delete to authenticated
using (owner_id = (select auth.uid()));

create policy "members read campaign membership" on public.campaign_members for select to authenticated
using (public.is_campaign_member(campaign_id));
create policy "gms manage campaign membership" on public.campaign_members for all to authenticated
using (public.is_campaign_gm(campaign_id)) with check (public.is_campaign_gm(campaign_id));
create policy "owners add initial gm membership" on public.campaign_members for insert to authenticated
with check (
  user_id = (select auth.uid()) and role = 'gm'
  and exists (select 1 from public.campaigns c where c.id = campaign_id and c.owner_id = (select auth.uid()))
);

create policy "members read characters" on public.characters for select to authenticated
using (public.is_campaign_member(campaign_id));
create policy "gms manage characters" on public.characters for all to authenticated
using (public.is_campaign_gm(campaign_id)) with check (public.is_campaign_gm(campaign_id));
create policy "players update owned characters" on public.characters for update to authenticated
using (owner_id = (select auth.uid()) and public.is_campaign_member(campaign_id))
with check (owner_id = (select auth.uid()) and public.is_campaign_member(campaign_id));

create policy "members read campaign assets" on public.campaign_assets for select to authenticated
using (public.is_campaign_member(campaign_id));
create policy "gms manage campaign assets" on public.campaign_assets for all to authenticated
using (public.is_campaign_gm(campaign_id)) with check (public.is_campaign_gm(campaign_id));

create policy "members read scenes" on public.scenes for select to authenticated
using (public.is_campaign_member(campaign_id));
create policy "gms manage scenes" on public.scenes for all to authenticated
using (public.is_campaign_gm(campaign_id)) with check (public.is_campaign_gm(campaign_id));

create policy "members read sessions" on public.sessions for select to authenticated
using (public.is_campaign_member(campaign_id));
create policy "gms manage sessions" on public.sessions for all to authenticated
using (public.is_campaign_gm(campaign_id)) with check (public.is_campaign_gm(campaign_id));

create policy "members read session events" on public.session_events for select to authenticated
using (exists (select 1 from public.sessions s where s.id = session_id and public.is_campaign_member(s.campaign_id)));
create policy "members create session events" on public.session_events for insert to authenticated
with check (
  actor_id = (select auth.uid())
  and exists (select 1 from public.sessions s where s.id = session_id and public.is_campaign_member(s.campaign_id))
);

create policy "members read items" on public.items for select to authenticated
using (public.is_campaign_member(campaign_id));
create policy "gms manage items" on public.items for all to authenticated
using (public.is_campaign_gm(campaign_id)) with check (public.is_campaign_gm(campaign_id));

create policy "members read inventory" on public.character_inventory for select to authenticated
using (exists (select 1 from public.characters c where c.id = character_id and public.is_campaign_member(c.campaign_id)));
create policy "gms manage inventory" on public.character_inventory for all to authenticated
using (exists (select 1 from public.characters c where c.id = character_id and public.is_campaign_gm(c.campaign_id)))
with check (exists (select 1 from public.characters c where c.id = character_id and public.is_campaign_gm(c.campaign_id)));

create policy "members read shops" on public.shops for select to authenticated
using (public.is_campaign_member(campaign_id));
create policy "gms manage shops" on public.shops for all to authenticated
using (public.is_campaign_gm(campaign_id)) with check (public.is_campaign_gm(campaign_id));
create policy "members read shop stock" on public.shop_stock for select to authenticated
using (exists (select 1 from public.shops s where s.id = shop_id and public.is_campaign_member(s.campaign_id)));
create policy "gms manage shop stock" on public.shop_stock for all to authenticated
using (exists (select 1 from public.shops s where s.id = shop_id and public.is_campaign_gm(s.campaign_id)))
with check (exists (select 1 from public.shops s where s.id = shop_id and public.is_campaign_gm(s.campaign_id)));

create policy "members read their purchase requests" on public.purchase_requests for select to authenticated
using (
  requested_by = (select auth.uid())
  or exists (select 1 from public.shops s where s.id = shop_id and public.is_campaign_gm(s.campaign_id))
);
create policy "players request purchases" on public.purchase_requests for insert to authenticated
with check (
  requested_by = (select auth.uid())
  and exists (
    select 1 from public.characters c join public.shops s on s.campaign_id = c.campaign_id
    where c.id = character_id and s.id = shop_id
      and c.owner_id = (select auth.uid()) and public.is_campaign_member(c.campaign_id)
  )
);
create policy "gms resolve purchases" on public.purchase_requests for update to authenticated
using (exists (select 1 from public.shops s where s.id = shop_id and public.is_campaign_gm(s.campaign_id)))
with check (exists (select 1 from public.shops s where s.id = shop_id and public.is_campaign_gm(s.campaign_id)));

create policy "members read allowed messages" on public.messages for select to authenticated
using (
  public.is_campaign_member(campaign_id)
  and (recipient_id is null or recipient_id = (select auth.uid()) or sender_id = (select auth.uid()) or public.is_campaign_gm(campaign_id))
);
create policy "members create messages" on public.messages for insert to authenticated
with check (sender_id = (select auth.uid()) and public.is_campaign_member(campaign_id));

create policy "members read addressed prompts" on public.prompts for select to authenticated
using (
  public.is_campaign_member(campaign_id)
  and (cardinality(audience) = 0 or (select auth.uid()) = any(audience) or public.is_campaign_gm(campaign_id))
);
create policy "gms manage prompts" on public.prompts for all to authenticated
using (public.is_campaign_gm(campaign_id)) with check (public.is_campaign_gm(campaign_id));

create policy "members manage own prompt response" on public.prompt_responses for all to authenticated
using (
  user_id = (select auth.uid())
  and exists (
    select 1 from public.prompts p where p.id = prompt_id
      and public.is_campaign_member(p.campaign_id)
      and (cardinality(p.audience) = 0 or (select auth.uid()) = any(p.audience))
  )
)
with check (
  user_id = (select auth.uid())
  and exists (
    select 1 from public.prompts p where p.id = prompt_id and p.status = 'open'
      and public.is_campaign_member(p.campaign_id)
      and (cardinality(p.audience) = 0 or (select auth.uid()) = any(p.audience))
  )
);

create policy "members read scene triggers" on public.scene_triggers for select to authenticated
using (exists (select 1 from public.scenes s where s.id = scene_id and public.is_campaign_member(s.campaign_id)));
create policy "gms manage scene triggers" on public.scene_triggers for all to authenticated
using (exists (select 1 from public.scenes s where s.id = scene_id and public.is_campaign_gm(s.campaign_id)))
with check (exists (select 1 from public.scenes s where s.id = scene_id and public.is_campaign_gm(s.campaign_id)));

create policy "members read session snapshots" on public.session_snapshots for select to authenticated
using (exists (select 1 from public.sessions s where s.id = session_id and public.is_campaign_member(s.campaign_id)));
create policy "gms manage session snapshots" on public.session_snapshots for all to authenticated
using (exists (select 1 from public.sessions s where s.id = session_id and public.is_campaign_gm(s.campaign_id)))
with check (exists (select 1 from public.sessions s where s.id = session_id and public.is_campaign_gm(s.campaign_id)));

insert into storage.buckets (id, name, public)
values ('campaign-media', 'campaign-media', false)
on conflict (id) do update set public = excluded.public;

create policy "members read campaign media" on storage.objects for select to authenticated
using (
  bucket_id = 'campaign-media'
  and public.is_campaign_member(((storage.foldername(name))[1])::uuid)
);
create policy "gms upload campaign media" on storage.objects for insert to authenticated
with check (
  bucket_id = 'campaign-media'
  and public.is_campaign_gm(((storage.foldername(name))[1])::uuid)
);
create policy "gms update campaign media" on storage.objects for update to authenticated
using (
  bucket_id = 'campaign-media'
  and public.is_campaign_gm(((storage.foldername(name))[1])::uuid)
)
with check (
  bucket_id = 'campaign-media'
  and public.is_campaign_gm(((storage.foldername(name))[1])::uuid)
);
create policy "gms delete campaign media" on storage.objects for delete to authenticated
using (
  bucket_id = 'campaign-media'
  and public.is_campaign_gm(((storage.foldername(name))[1])::uuid)
);

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'messages', 'prompt_responses', 'prompts', 'purchase_requests', 'session_events', 'sessions'
  ] loop
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = table_name
    ) then
      execute format('alter publication supabase_realtime add table public.%I', table_name);
    end if;
  end loop;
end;
$$;

revoke execute on function public.touch_updated_at() from public, anon, authenticated;
