alter table public.scene_triggers add column run_once boolean not null default false,add column updated_at timestamptz not null default now();
create table public.automation_executions(id uuid primary key default gen_random_uuid(),trigger_id uuid not null references public.scene_triggers(id) on delete cascade,session_id uuid not null references public.sessions(id) on delete cascade,idempotency_key text not null,status text not null check(status in ('scheduled','completed','failed')),run_at timestamptz not null default now(),result jsonb not null default '{}',created_at timestamptz not null default now(),unique(trigger_id,session_id,idempotency_key));
alter table public.automation_executions enable row level security;grant select on public.automation_executions to authenticated;create policy "gms read automation executions" on public.automation_executions for select to authenticated using(exists(select 1 from public.sessions s where s.id=session_id and public.is_campaign_gm(s.campaign_id)));

create or replace function private.apply_roll30_trigger(target_trigger uuid,target_session uuid,execution_key text)
returns public.session_events language plpgsql security definer set search_path=public as $$
declare rule public.scene_triggers;sess public.sessions;effect jsonb;next_state jsonb;next_round integer;result public.session_events;character_row public.characters;
begin
  select * into rule from public.scene_triggers where id=target_trigger and enabled;select * into sess from public.sessions where id=target_session for update;if rule.id is null or sess.id is null or not exists(select 1 from public.scenes where id=rule.scene_id and campaign_id=sess.campaign_id) then raise exception 'Trigger and session do not match';end if;if coalesce((rule.trigger->>'min_round')::integer,0)>sess.round then raise exception 'Trigger condition is not met';end if;if rule.run_once and exists(select 1 from public.automation_executions where trigger_id=rule.id and session_id=sess.id and status='completed') then raise exception 'This one-time trigger already ran';end if;
  next_state:=coalesce(sess.state,'{}');next_round:=sess.round;for effect in select value from jsonb_array_elements(coalesce(rule.effects,'[]')) loop case effect->>'type' when 'show_fog' then next_state:=jsonb_set(next_state,'{fog}','true',true);when 'clear_fog' then next_state:=jsonb_set(next_state,'{fog}','false',true);when 'advance_round' then next_round:=next_round+1;when 'toggle_object' then update public.scene_objects set state=jsonb_set(state,'{active}',to_jsonb(not coalesce((state->>'active')::boolean,false)),true) where id=(effect->>'object_id')::uuid and scene_id=rule.scene_id;when 'set_object_state' then update public.scene_objects set state=jsonb_set(state,'{active}',to_jsonb(coalesce((effect->>'active')::boolean,false)),true) where id=(effect->>'object_id')::uuid and scene_id=rule.scene_id;when 'spawn_character' then select * into character_row from public.characters where id=(effect->>'character_id')::uuid and campaign_id=sess.campaign_id;if character_row.id is not null then insert into public.session_tokens(session_id,character_id,name,x,y,speed) values(sess.id,character_row.id,character_row.name,greatest(2,least(98,coalesce((effect->>'x')::integer,50))),greatest(2,least(98,coalesce((effect->>'y')::integer,50))),coalesce((character_row.sheet->>'speed')::numeric,30)) on conflict(session_id,character_id) do nothing;end if;when 'message' then insert into public.messages(campaign_id,sender_id,kind,body) values(sess.campaign_id,auth.uid(),'action',jsonb_build_object('text',left(coalesce(effect->>'text','Automation ran'),2000)));else raise exception 'Unsupported automation effect: %',effect->>'type';end case;end loop;
  update public.sessions set state=next_state,round=next_round,updated_at=now() where id=sess.id;insert into public.session_events(session_id,actor_id,event_type,payload) values(sess.id,auth.uid(),'trigger_executed',jsonb_build_object('trigger_id',rule.id,'name',rule.name,'effects',rule.effects,'key',execution_key)) returning * into result;update public.automation_executions set status='completed',result=jsonb_build_object('event_id',result.id) where trigger_id=rule.id and session_id=sess.id and idempotency_key=execution_key;return result;
end; $$;

drop function public.execute_roll30_trigger(uuid,uuid);
create or replace function public.execute_roll30_trigger(target_trigger uuid,target_session uuid,execution_key text default null)
returns public.session_events language plpgsql security definer set search_path=public as $$
declare rule public.scene_triggers;sess public.sessions;key text:=coalesce(nullif(execution_key,''),gen_random_uuid()::text);delay_seconds integer;result public.session_events;
begin select * into rule from public.scene_triggers where id=target_trigger and enabled;select * into sess from public.sessions where id=target_session;if rule.id is null or sess.id is null or not public.is_campaign_gm(sess.campaign_id) then raise exception 'Only the GM can execute this trigger';end if;if exists(select 1 from public.automation_executions where trigger_id=rule.id and session_id=sess.id and idempotency_key=key) then raise exception 'Execution key already exists';end if;delay_seconds:=greatest(0,least(86400,coalesce((rule.trigger->>'delay_seconds')::integer,0)));insert into public.automation_executions(trigger_id,session_id,idempotency_key,status,run_at) values(rule.id,sess.id,key,'scheduled',now()+make_interval(secs=>delay_seconds));if delay_seconds>0 then insert into public.session_events(session_id,actor_id,event_type,payload) values(sess.id,auth.uid(),'trigger_scheduled',jsonb_build_object('trigger_id',rule.id,'name',rule.name,'run_at',now()+make_interval(secs=>delay_seconds),'key',key)) returning * into result;return result;end if;return private.apply_roll30_trigger(rule.id,sess.id,key);end; $$;

create or replace function public.run_due_roll30_automations(target_session uuid)
returns integer language plpgsql security definer set search_path=public as $$
declare execution public.automation_executions;processed integer:=0;sess public.sessions;
begin select * into sess from public.sessions where id=target_session;if sess.id is null or not public.is_campaign_gm(sess.campaign_id) then raise exception 'Only the GM can run due automation';end if;for execution in select * from public.automation_executions where session_id=target_session and status='scheduled' and run_at<=now() order by run_at for update skip locked loop perform private.apply_roll30_trigger(execution.trigger_id,execution.session_id,execution.idempotency_key);processed:=processed+1;end loop;return processed;end; $$;

alter table public.session_snapshots add column session_round integer,add column session_active_turn integer,add column scene_id uuid references public.scenes(id) on delete set null;
create or replace function public.snapshot_roll30_session(target_session uuid,snapshot_label text default null)
returns public.session_snapshots language plpgsql security definer set search_path=public as $$
declare current_session public.sessions;token_state jsonb;snapshot_state jsonb;result public.session_snapshots;
begin select * into current_session from public.sessions where id=target_session for update;if current_session.id is null or not public.is_campaign_gm(current_session.campaign_id) then raise exception 'Only the GM can save a snapshot';end if;select coalesce(jsonb_agg(jsonb_build_object('id',t.id,'character_id',t.character_id,'name',t.name,'x',t.x,'y',t.y,'speed',t.speed) order by t.created_at,t.id),'[]') into token_state from public.session_tokens t where t.session_id=target_session;snapshot_state:=jsonb_set(coalesce(current_session.state,'{}'),'{tokens}',token_state,true);insert into public.session_snapshots(session_id,created_by,label,state,session_round,session_active_turn,scene_id) values(target_session,auth.uid(),coalesce(nullif(trim(snapshot_label),''),'Snapshot'),snapshot_state,current_session.round,current_session.active_turn,current_session.scene_id) returning * into result;insert into public.session_events(session_id,actor_id,event_type,payload) values(target_session,auth.uid(),'snapshot_saved',jsonb_build_object('snapshot_id',result.id,'label',result.label));return result;end; $$;
create or replace function public.restore_roll30_snapshot(target_snapshot uuid)
returns public.sessions language plpgsql security definer set search_path=public as $$
declare snap public.session_snapshots;result public.sessions;restored_state jsonb;
begin select * into snap from public.session_snapshots where id=target_snapshot;select * into result from public.sessions where id=snap.session_id for update;if snap.id is null or result.id is null or not public.is_campaign_gm(result.campaign_id) then raise exception 'Only the GM can restore a snapshot';end if;delete from public.session_tokens where session_id=result.id;insert into public.session_tokens(id,session_id,character_id,name,x,y,speed) select case when token?'id' then (token->>'id')::uuid else gen_random_uuid() end,result.id,character.id,coalesce(nullif(token->>'name',''),character.name),greatest(2,least(98,coalesce((token->>'x')::integer,50))),greatest(2,least(98,coalesce((token->>'y')::integer,50))),greatest(1,coalesce((token->>'speed')::numeric,(character.sheet->>'speed')::numeric,30)) from jsonb_array_elements(coalesce(snap.state->'tokens','[]')) token join public.characters character on character.id=(token->>'character_id')::uuid and character.campaign_id=result.campaign_id;restored_state:=coalesce(snap.state,'{}')-'tokens';update public.sessions set state=restored_state,round=coalesce(snap.session_round,round),active_turn=coalesce(snap.session_active_turn,active_turn),scene_id=coalesce(snap.scene_id,scene_id),updated_at=now() where id=result.id returning * into result;insert into public.session_events(session_id,actor_id,event_type,payload) values(result.id,auth.uid(),'snapshot_restored',jsonb_build_object('snapshot_id',snap.id,'label',snap.label));return result;end; $$;

create or replace function public.advance_roll30_turn(target_session uuid)
returns public.sessions language plpgsql security definer set search_path=public as $$
declare result public.sessions;initiative_count integer;next_turn integer;next_round integer;
begin select * into result from public.sessions where id=target_session for update;if result.id is null or not public.is_campaign_gm(result.campaign_id) then raise exception 'Only the GM can advance the shared turn';end if;initiative_count:=jsonb_array_length(coalesce(result.state->'initiative','[]'));next_turn:=result.active_turn+1;next_round:=result.round;if initiative_count>0 and next_turn>=initiative_count then next_turn:=0;next_round:=result.round+1;perform public.snapshot_roll30_session(result.id,'Before round '||next_round);end if;update public.sessions set active_turn=next_turn,round=next_round,updated_at=now() where id=target_session returning * into result;insert into public.session_events(session_id,actor_id,event_type,payload) values(target_session,auth.uid(),'turn_advanced',jsonb_build_object('active_turn',result.active_turn,'round',result.round));return result;end; $$;

create or replace function public.rewind_roll30_round(target_session uuid)
returns public.sessions language plpgsql security definer set search_path=public as $$
declare snapshot_id uuid;sess public.sessions;
begin select * into sess from public.sessions where id=target_session;if sess.id is null or not public.is_campaign_gm(sess.campaign_id) then raise exception 'Only the GM can rewind a round';end if;select id into snapshot_id from public.session_snapshots where session_id=target_session and label like 'Before round %' order by created_at desc limit 1;if snapshot_id is null then raise exception 'No automatic round checkpoint exists yet';end if;return public.restore_roll30_snapshot(snapshot_id);end; $$;

revoke all on function public.execute_roll30_trigger(uuid,uuid,text) from public,anon;revoke all on function public.run_due_roll30_automations(uuid) from public,anon;revoke all on function public.rewind_roll30_round(uuid) from public,anon;
grant execute on function public.execute_roll30_trigger(uuid,uuid,text) to authenticated;grant execute on function public.run_due_roll30_automations(uuid) to authenticated;grant execute on function public.rewind_roll30_round(uuid) to authenticated;
