drop policy if exists "members read shop stock" on public.shop_stock;
create policy "members read available shop stock" on public.shop_stock for select to authenticated
using (exists(select 1 from public.shops s where s.id=shop_id and public.is_campaign_member(s.campaign_id) and (not hidden or public.is_campaign_gm(s.campaign_id))));

create or replace function private.roll30_purchase_total(shop public.shops,stock public.shop_stock,amount integer)
returns integer language sql immutable set search_path=public as $$
  select greatest(0,round(stock.price*amount*(100-greatest(-500,least(100,coalesce((shop.settings->>'discount')::numeric,0))))/100.0)::integer)
$$;

create or replace function public.request_roll30_purchase(target_shop uuid,target_item uuid,target_character uuid,requested_quantity integer default 1)
returns public.purchase_requests language plpgsql security definer set search_path=public as $$
declare shop public.shops;stock public.shop_stock;character public.characters;result public.purchase_requests;mode text;gp integer;total integer;
begin
  if requested_quantity<1 then raise exception 'Quantity must be at least one';end if;select * into shop from public.shops where id=target_shop;if shop.id is null or not public.is_campaign_member(shop.campaign_id) then raise exception 'Shop not found';end if;select * into character from public.characters where id=target_character for update;if character.id is null or character.campaign_id<>shop.campaign_id then raise exception 'Character is not in this campaign';end if;if character.owner_id is distinct from auth.uid() and not public.is_campaign_gm(shop.campaign_id) then raise exception 'You can only purchase for your own character';end if;select * into stock from public.shop_stock where shop_id=target_shop and item_id=target_item for update;if stock.item_id is null or (stock.hidden and not public.is_campaign_gm(shop.campaign_id)) then raise exception 'Item is no longer available';end if;if stock.quantity is not null and stock.quantity<requested_quantity then raise exception 'Not enough stock';end if;
  mode:=coalesce(shop.settings->>'mode','approval');insert into public.purchase_requests(shop_id,item_id,character_id,quantity,requested_by,status) values(target_shop,target_item,target_character,requested_quantity,auth.uid(),case when mode='automatic' then 'completed' else 'pending' end) returning * into result;if mode<>'automatic' then return result;end if;
  gp:=coalesce((character.sheet->'currency'->>'gp')::integer,0);total:=private.roll30_purchase_total(shop,stock,requested_quantity);if gp<total then raise exception 'Character cannot afford this purchase';end if;update public.characters set sheet=jsonb_set(character.sheet,'{currency,gp}',to_jsonb(gp-total),true),sheet_revision=sheet_revision+1,updated_at=now() where id=character.id;insert into public.character_inventory(character_id,item_id,quantity) values(character.id,target_item,requested_quantity) on conflict(character_id,item_id) do update set quantity=public.character_inventory.quantity+excluded.quantity;if stock.quantity is not null then update public.shop_stock set quantity=quantity-requested_quantity where shop_id=stock.shop_id and item_id=stock.item_id;end if;update public.purchase_requests set resolved_at=now() where id=result.id returning * into result;return result;
end; $$;

create or replace function public.resolve_roll30_purchase(target_request uuid,approve boolean)
returns public.purchase_requests language plpgsql security definer set search_path=public as $$
declare request_row public.purchase_requests;shop_row public.shops;stock_row public.shop_stock;character_row public.characters;gp integer;total integer;
begin
  select * into request_row from public.purchase_requests where id=target_request for update;if request_row.id is null then raise exception 'Purchase request not found';end if;select * into shop_row from public.shops where id=request_row.shop_id;if not public.is_campaign_gm(shop_row.campaign_id) then raise exception 'Only the GM can resolve purchases';end if;if request_row.status<>'pending' then raise exception 'Purchase request is already resolved';end if;if not approve then update public.purchase_requests set status='declined',resolved_at=now() where id=target_request returning * into request_row;return request_row;end if;
  select * into stock_row from public.shop_stock where shop_id=request_row.shop_id and item_id=request_row.item_id for update;if stock_row.item_id is null then raise exception 'Item is no longer stocked';end if;if stock_row.quantity is not null and stock_row.quantity<request_row.quantity then raise exception 'Not enough stock';end if;select * into character_row from public.characters where id=request_row.character_id for update;gp:=coalesce((character_row.sheet->'currency'->>'gp')::integer,0);total:=private.roll30_purchase_total(shop_row,stock_row,request_row.quantity);if gp<total then raise exception 'Character cannot afford this purchase';end if;update public.characters set sheet=jsonb_set(sheet,'{currency,gp}',to_jsonb(gp-total),true),sheet_revision=sheet_revision+1,updated_at=now() where id=character_row.id;insert into public.character_inventory(character_id,item_id,quantity) values(character_row.id,request_row.item_id,request_row.quantity) on conflict(character_id,item_id) do update set quantity=public.character_inventory.quantity+excluded.quantity;if stock_row.quantity is not null then update public.shop_stock set quantity=quantity-request_row.quantity where shop_id=stock_row.shop_id and item_id=stock_row.item_id;end if;update public.purchase_requests set status='completed',resolved_at=now() where id=target_request returning * into request_row;return request_row;
end; $$;

revoke all on function public.request_roll30_purchase(uuid,uuid,uuid,integer) from public,anon;
revoke all on function public.resolve_roll30_purchase(uuid,boolean) from public,anon;
grant execute on function public.request_roll30_purchase(uuid,uuid,uuid,integer) to authenticated;
grant execute on function public.resolve_roll30_purchase(uuid,boolean) to authenticated;
